"""readGEF against the synthetic GEFs in tests/gef_fixtures/.

Mirrors NDI-matlab's TestReadGEF, fixture for fixture, so the two readers
are held to the same file rather than each to its own.

The fixtures are generated by bscholl-genomics-python's
cloudFriendly/make_gef_conformance_fixtures.py, which writes the same files
into both NDI repos, and are committed here. The generator lives there
because both repos consume it and neither may own the other: NDI-python
follows NDI-matlab, so it cannot be the source NDI-matlab's fixtures come
from. Each varies ONE thing readGEF probes for, so a failure names the
probe that broke. Three exist because the
failure they catch is silent:

  * gef_basic writes the extent attributes on the BIN GROUP, not the file
    root. Probing only the root yields a 1x1 pyramid, and a fixture that
    writes them at the root agrees with that bug -- so gef_rootattrs
    covers the root case separately rather than being the only case.
  * gef_badbox's attribute box does not contain the records; it must lose
    to the data rather than silently shifting the origin.
  * gef_uint8 stores counts as uint8. Clipping in the narrow type
    saturates large counts at 255 without erroring.

Records are the same in every fixture: 6 records over 3 genes in blocks of
3, 1 and 2, x in 10..31 and y in 50..71. y is offset from x so a
transposing reader diverges rather than coincidentally agreeing.
"""

from __future__ import annotations

import pathlib

import numpy as np
import pytest

from ndi.fun.doc_gene import readGEF

FIXTURES = pathlib.Path(__file__).resolve().parent / "gef_fixtures"

X = [10, 11, 12, 20, 30, 31]
Y = [50, 51, 52, 60, 70, 71]
C = [1, 2, 200, 7, 8, 9]
GENE_INDEX = [0, 0, 0, 1, 2, 2]


def gef(which: str) -> str:
    p = FIXTURES / f"gef_{which}.gef"
    assert p.is_file(), f"{p} missing; regenerate with make_gef_conformance_fixtures.py"
    return str(p)


def test_reads_records_and_genes():
    x, y, gi, c, gid, gnm, meta = readGEF(gef("basic"))

    assert len(x) == 6
    assert meta["nRecords"] == 6
    assert meta["nGenes"] == 3
    assert gid == ["ENSG1", "ENSG2", "ENSG3"]
    assert gnm == ["Aaa", "Bbb", "Ccc"]

    # gene_index is ZERO-BASED and follows the offset blocks.
    assert list(gi) == GENE_INDEX
    assert x.dtype == np.int32
    assert c.dtype == np.uint16
    assert list(x) == X
    assert list(y) == Y
    assert list(c) == C


def test_chip_serial_and_resolution():
    *_, meta = readGEF(gef("basic"))
    assert meta["chipSerial"] == "TESTCHIP01"
    assert meta["resolutionNm"] == 500


def test_extent_attributes_are_found_off_the_root():
    """On the bin group. A root-only probe would fall back to the data."""
    *_, meta = readGEF(gef("basic"))
    assert meta["box"] == (0, 0, 99, 99)
    assert "/geneExp/bin1" in meta["boxSource"]


def test_extent_attributes_at_the_root_also_work():
    *_, meta = readGEF(gef("rootattrs"))
    assert meta["box"] == (0, 0, 99, 99)
    assert "attrs" in meta["boxSource"]


def test_disagreeing_attributes_lose_to_the_data():
    """The data cannot be wrong about its own extent."""
    x, y, *_, meta = readGEF(gef("badbox"))
    assert meta["boxSource"] == "data"
    assert meta["box"] == (int(x.min()), int(y.min()), int(x.max()), int(y.max()))


def test_counts_clip_in_a_wide_type():
    """uint8 counts: clipping in the narrow type saturates these at 255."""
    *_, c, _, _, meta = readGEF(gef("uint8"))
    assert int(c.max()) == 200
    assert meta["nCountsClamped"] == 0


def test_count_ceiling_clamps_and_reports():
    *_, c, _, _, meta = readGEF(gef("basic"), countCeiling=5)
    assert int(c.max()) == 5
    assert meta["nCountsClamped"] == 4  # 200, 7, 8, 9


def test_alternate_field_names_are_probed():
    x, _, _, c, _, _, meta = readGEF(gef("altfields"))
    assert meta["fields"]["x"] == "X"
    assert meta["fields"]["count"] == "MIDCount"
    assert list(x) == X
    assert list(c) == C


def test_alternate_layout_is_probed():
    *_, meta = readGEF(gef("altroot"))
    assert meta["root"] == "/wholeExp/bin1"
    assert meta["exprDataset"].endswith("cellBin")


def test_stat_gene_cross_check():
    """SAW's own MIDcount is a third source for a number we derive.

    The fixture carries the true per-gene sums, so a reader that assigns
    records to the wrong genes disagrees with it.
    """
    _, _, gi, c, _, _, meta = readGEF(gef("basic"))
    assert list(meta["statTotals"]) == [203, 7, 17]

    derived = np.bincount(gi, weights=c.astype(np.int64), minlength=3)
    assert list(derived) == list(meta["statTotals"])


def test_probe_only_reads_no_records():
    x, y, gi, c, gid, _, meta = readGEF(gef("basic"), probeOnly=True)

    assert len(x) == 0 and len(y) == 0 and len(gi) == 0 and len(c) == 0

    # The gene table and the record COUNT are still exact: both come from
    # the gene table, which probeOnly does read. That is the point -- a GUI
    # can show what is in a file without the long read.
    assert meta["nRecords"] == 6
    assert meta["nGenes"] == 3
    assert gid == ["ENSG1", "ENSG2", "ENSG3"]

    # The box is reported UNVALIDATED: with no records there is nothing to
    # check it against, and a caller must be able to tell.
    assert "unvalidated" in meta["boxSource"]


def test_probe_only_still_names_the_fields():
    """The field probe must not depend on reading records."""
    *_, meta = readGEF(gef("altfields"), probeOnly=True)
    assert meta["fields"]["x"] == "X"
    assert meta["fields"]["count"] == "MIDCount"


def test_probe_only_does_not_touch_the_expression_dataset(monkeypatch):
    """probeOnly's promise is about COST, so assert no record is read.

    Checking only that the arrays come back empty would pass an
    implementation that read all 10^8 records and threw them away.
    """
    import h5py

    reads: list[str] = []
    real = h5py.Dataset.__getitem__

    def spy(self, key):
        reads.append(self.name)
        return real(self, key)

    monkeypatch.setattr(h5py.Dataset, "__getitem__", spy)
    readGEF(gef("basic"), probeOnly=True)

    assert not any(r.endswith("expression") for r in reads), (
        f"probeOnly read the expression dataset: {reads}"
    )


def test_max_genes_limits():
    _, _, gi, _, gid, _, meta = readGEF(gef("basic"), maxGenes=2)
    assert meta["nGenes"] == 2
    assert meta["nGenesInFile"] == 3
    assert len(gid) == 2
    assert meta["nRecords"] == 4  # 3 + 1
    assert int(gi.max()) == 1


def test_not_a_gef_is_named():
    with pytest.raises(KeyError, match="No .gene, expression. pair"):
        readGEF(gef("notagef"))
