"""Read + verify the time_convert symmetry artifacts (time namespace).

Two layers:

  * Python self-consistency: re-run the scenario and confirm the current
    ``time_convert`` reproduces the recorded ``pythonArtifacts`` outputs (a
    cross-run regression guard, independent of MATLAB).
  * Cross-language symmetry: if ``matlabArtifacts/time/.../timeConvertCases.json``
    is present (generated by the MATLAB side), assert MATLAB's ``out_*`` values
    match Python's. This skips until the MATLAB artifact exists -- FULL closure
    needs the MATLAB runtime.

Run the matching ``make_artifacts`` test first to populate pythonArtifacts.
"""

import json

import pytest

from tests.symmetry._time_scenario import run_cases
from tests.symmetry.conftest import MATLAB_ARTIFACTS, PYTHON_ARTIFACTS

_REL = "time/timeConvert/testTimeConvertArtifacts/timeConvertCases.json"
PY_FILE = PYTHON_ARTIFACTS / _REL
ML_FILE = MATLAB_ARTIFACTS / _REL

_KEY = ("in_ref", "in_clock", "in_epoch", "in_time", "out_ref", "out_clock")
_OUT = ("out_time", "out_epoch", "msg")


def _index(cases):
    return {tuple(c[k] for k in _KEY): c for c in cases}


def test_python_artifacts_reproduce():
    if not PY_FILE.exists():
        pytest.skip(f"{PY_FILE} missing — run make_artifacts/time/test_time_convert.py first")
    recorded = _index(json.loads(PY_FILE.read_text())["cases"])
    fresh = _index(run_cases())
    assert recorded.keys() == fresh.keys()
    for key, rec in recorded.items():
        f = fresh[key]
        for field in _OUT:
            assert rec[field] == f[field], f"{key} {field}: recorded={rec[field]} fresh={f[field]}"


def test_matlab_python_symmetry():
    if not ML_FILE.exists():
        pytest.skip(
            f"{ML_FILE} missing — MATLAB time-convert artifacts not generated yet "
            "(full cross-language closure needs the MATLAB runtime)"
        )
    if not PY_FILE.exists():
        pytest.skip(f"{PY_FILE} missing — run make_artifacts/time/test_time_convert.py first")
    py = _index(json.loads(PY_FILE.read_text())["cases"])
    ml = _index(json.loads(ML_FILE.read_text())["cases"])
    assert py.keys() == ml.keys(), "MATLAB and Python ran different time_convert cases"
    for key, p in py.items():
        m = ml[key]
        pt, mt = p["out_time"], m["out_time"]
        if pt is None or mt is None:
            assert pt == mt, f"{key} out_time: py={pt} matlab={mt}"
        else:
            assert abs(float(pt) - float(mt)) < 1e-6, f"{key} out_time: py={pt} matlab={mt}"
        assert p["out_epoch"] == m["out_epoch"], f"{key} out_epoch"
        assert p["msg"] == m["msg"], f"{key} msg"
