"""Shared fixtures and configuration for NDI symmetry tests.

Symmetry tests verify cross-language parity between NDI-python and NDI-matlab.
They are separated from the regular test suite because they depend on artifacts
that may have been generated by a prior MATLAB (or Python) run.
"""

import tempfile
from pathlib import Path

# Base directory where all symmetry artifacts live:
#   <tempdir>/NDI/symmetryTest/<sourceType>/<namespace>/<class>/<test>/
SYMMETRY_BASE = Path(tempfile.gettempdir()) / "NDI" / "symmetryTest"
PYTHON_ARTIFACTS = SYMMETRY_BASE / "pythonArtifacts"
MATLAB_ARTIFACTS = SYMMETRY_BASE / "matlabArtifacts"

SOURCE_TYPES = ["matlabArtifacts", "pythonArtifacts"]
