"""Shared fixtures and configuration for NDI symmetry tests.

Symmetry tests verify cross-language parity between NDI-python and NDI-matlab.
They are separated from the regular test suite because they depend on artifacts
that may have been generated by a prior MATLAB (or Python) run.

NDI_SYMMETRY_REQUIRE_ARTIFACTS
------------------------------
Every read-side test guards on ``if not artifact_dir.exists(): pytest.skip(...)``
so that a developer without a MATLAB licence can still run the Python half.  In
CI that same guard is a hole: with the artifact root absent -- the exact state
after a MATLAB Stage 1 that produced nothing -- the CI command
``pytest tests/symmetry/read_artifacts/ -v --tb=short`` reported *42 skipped*
and exited 0.  A cross-language parity job cannot be allowed to pass having made
zero comparisons.

Setting ``NDI_SYMMETRY_REQUIRE_ARTIFACTS=1`` (CI does) turns every skip in this
tree into a failure.  It is deliberately implemented once, as a report wrapper,
rather than by editing the 35 individual ``pytest.skip`` call sites: the next
test to be added inherits the guarantee instead of quietly opting out of it.
"""

import os
import tempfile
from collections.abc import Mapping
from pathlib import Path

import pytest

# Base directory where all symmetry artifacts live:
#   <tempdir>/NDI/symmetryTest/<sourceType>/<namespace>/<class>/<test>/
SYMMETRY_BASE = Path(tempfile.gettempdir()) / "NDI" / "symmetryTest"
PYTHON_ARTIFACTS = SYMMETRY_BASE / "pythonArtifacts"
MATLAB_ARTIFACTS = SYMMETRY_BASE / "matlabArtifacts"

SOURCE_TYPES = ["matlabArtifacts", "pythonArtifacts"]

REQUIRE_ARTIFACTS_ENV = "NDI_SYMMETRY_REQUIRE_ARTIFACTS"

_TRUTHY = frozenset({"1", "true", "yes", "on"})


def require_artifacts_enabled(environ: Mapping[str, str] | None = None) -> bool:
    """Return True when missing symmetry artifacts must fail rather than skip."""
    env = os.environ if environ is None else environ
    return str(env.get(REQUIRE_ARTIFACTS_ENV, "")).strip().lower() in _TRUTHY


def _skip_reason(report) -> str:
    """Extract the human-readable reason from a skipped report."""
    longrepr = getattr(report, "longrepr", None)
    if isinstance(longrepr, tuple) and len(longrepr) == 3:
        path, lineno, reason = longrepr
        return f"{reason} ({path}:{lineno})"
    return str(longrepr)


@pytest.hookimpl(hookwrapper=True, trylast=True)
def pytest_runtest_makereport(item, call):
    """Convert skips into failures when artifacts are required.

    Runs as a wrapper so it sees the finished report regardless of which phase
    (setup or call) raised the skip, and regardless of whether the skip came
    from ``pytest.skip`` in a test body, a helper, or a fixture.
    """
    outcome = yield
    if not require_artifacts_enabled():
        return
    report = outcome.get_result()
    if not report.skipped:
        return
    reason = _skip_reason(report)
    report.outcome = "failed"
    report.longrepr = (
        f"{REQUIRE_ARTIFACTS_ENV} is set, so a skipped symmetry test is a failure.\n"
        f"Original skip reason: {reason}\n"
        f"Symmetry artifact root: {SYMMETRY_BASE}\n"
        f"  matlabArtifacts exists: {MATLAB_ARTIFACTS.is_dir()}\n"
        f"  pythonArtifacts exists: {PYTHON_ARTIFACTS.is_dir()}\n"
        f"A green symmetry run that compared nothing is worse than a red one: "
        f"either the producing stage did not run, or it wrote its artifacts "
        f"somewhere this process does not look."
    )
