"""
ndi.document - NDI database storage item

The ndi.ndi_document class is the primary method for storing data in the NDI database.
Each document has a specific schema type (e.g., 'base', 'session', 'stimulus').

Important Rules for Creating Documents:
1. Do not provide 'base.id' or 'base.datestamp' manually. These are automatically
   generated by the system to ensure uniqueness and accuracy.
2. Use the document_properties dict to create new versions or copies of documents.
3. When specifying document_type, use the name without '.json' extension.
"""

import json
import math
import shutil
import warnings
from copy import deepcopy
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional, Union

try:
    import pandas as pd

    HAS_PANDAS = True
except ImportError:
    HAS_PANDAS = False

try:
    from did.document import Document as DIDDocument
except ImportError:
    DIDDocument = None

from .common import ndi_common_PathConstants, timestamp
from .ido import ndi_ido

#: MATLAB reads this out of ``ndi.common.PathConstants.CommonFolder/config``
#: to shorten ``to_table`` column names.
_TABLE_ABBREVIATION_FILE = "ndi_document2table_abbreviations.json"


def _json_safe(value: Any) -> Any:
    """Replace NaN and Inf with None, as MATLAB's ConvertInfAndNaN does.

    ``jsonencode(..., 'ConvertInfAndNaN', true)`` writes ``null`` for both.
    Python's ``json.dump`` writes the bare tokens ``NaN`` and ``Infinity``
    instead, which are not JSON -- a document carrying an unmeasured value
    produced a file that ``json.load`` accepts but no other reader has to.
    """
    if isinstance(value, float) and (math.isnan(value) or math.isinf(value)):
        return None
    if isinstance(value, dict):
        return {k: _json_safe(v) for k, v in value.items()}
    if isinstance(value, (list, tuple)):
        return [_json_safe(v) for v in value]
    return value


def _is_struct_array(value: Any) -> bool:
    """True for a non-empty list of dicts -- MATLAB's struct array."""
    return isinstance(value, list) and bool(value) and all(isinstance(e, dict) for e in value)


def _definition_to_doc_type(definition: str) -> str:
    """Turn a superclass ``definition`` path into a document type name.

    Definitions name their target through a path VARIABLE:
    ``$NDIDOCUMENTPATH/element.json`` for NDI's own documents,
    ``$NDICALCDOCUMENTPATH/vision/contrast_tuning.json`` for ones shipped
    by NDIcalc-vis-matlab. MATLAB registers both as DID globals
    (ndi.common.PathConstants), so both resolve there.

    Here they resolve to the same folder, because ndi_install.py copies
    each dependency's ``ndi_common`` tree into NDI-python's own. So every
    variable is stripped rather than only ``$NDIDOCUMENTPATH`` -- which is
    what previously left ``$NDICALCDOCUMENTPATH/...`` as a literal path,
    unfindable, and silently skipped.
    """
    import re

    return re.sub(r"^\$[A-Z]+PATH/", "", definition).replace(".json", "")


class ndi_document:
    """NDI document class for database storage.

    The ndi_document object is the primary method for storing data in the NDI database.
    Each document has a specific schema type and contains structured properties.

    Attributes:
        document_properties (dict): The document's data as a nested dictionary.

    Example:
        # Create a new document
        doc = ndi_document('base', **{'base.name': 'my_document'})

        # Access properties
        doc_id = doc.id
        doc_class = doc.doc_class()

        # Set session
        doc = doc.set_session_id('session_12345')
    """

    def __init__(self, document_type: Union[str, dict, "ndi_document"] = "base", **kwargs):
        """Create a new NDI document.

        Args:
            document_type: Either:
                - A string document type name (e.g., 'base', 'stimulus')
                - A dict containing document properties (for loading existing)
                - Another ndi_document object (for copying)
                - A DIDDocument object (for conversion, if DID-python is installed)
            **kwargs: Name/value pairs for setting document properties.
                      Property names should be fully qualified (e.g., 'base.name').

        Example:
            doc = ndi_document('base', **{'base.name': 'my_doc'})
            doc = ndi_document(existing_doc.document_properties)
        """
        if isinstance(document_type, dict):
            # Loading from existing properties
            self._document_properties = deepcopy(document_type)
            self._normalize_depends_on()
        elif isinstance(document_type, ndi_document):
            # Copy from another ndi_document
            self._document_properties = deepcopy(document_type.document_properties)
        elif DIDDocument is not None and isinstance(document_type, DIDDocument):
            # Convert from DIDDocument
            self._document_properties = deepcopy(document_type.document_properties)
            self._normalize_depends_on()
        else:
            # Create new from schema
            self._document_properties = self.read_blank_definition(document_type)

            # Generate new ID and timestamp
            ido = ndi_ido()
            self._document_properties["base"]["id"] = ido.id
            self._document_properties["base"]["datestamp"] = timestamp()

            # Set additional properties from kwargs
            for key, value in kwargs.items():
                self._set_nested_property(key, value)

    def _normalize_depends_on(self):
        """Ensure depends_on, files.file_info, and superclasses are always lists.

        MATLAB's jsonencode converts single-element cell arrays to scalars,
        so documents downloaded from the cloud (or created by MATLAB) may
        have ``depends_on``, ``files.file_info``, or
        ``document_class.superclasses`` as a bare dict instead of a list.
        Normalizing here guarantees that downstream code (including
        DID-python's ``doc_to_sql`` / ``_serialize_depends_on`` /
        ``_get_superclass_str`` and all NDI code that iterates over these
        fields) always sees a list.
        """
        dep = self._document_properties.get("depends_on")
        if isinstance(dep, dict):
            self._document_properties["depends_on"] = [dep]

        files = self._document_properties.get("files")
        if isinstance(files, dict):
            fi = files.get("file_info")
            if isinstance(fi, dict):
                files["file_info"] = [fi]

        dc = self._document_properties.get("document_class")
        if isinstance(dc, dict):
            sc = dc.get("superclasses")
            if isinstance(sc, dict):
                dc["superclasses"] = [sc]

    @property
    def document_properties(self) -> dict:
        """The document's properties as a nested dictionary."""
        return self._document_properties

    @property
    def id(self) -> str:
        """Return the document's unique identifier."""
        return self._document_properties.get("base", {}).get("id", "")

    @property
    def session_id(self) -> str:
        """Return the document's session identifier."""
        return self._document_properties.get("base", {}).get("session_id", "")

    def set_session_id(self, session_id: str) -> "ndi_document":
        """Set the session ID for this document.

        Args:
            session_id: The session identifier to set.

        Returns:
            Self for method chaining.
        """
        self._document_properties["base"]["session_id"] = session_id
        return self

    def _set_nested_property(self, path: str, value: Any) -> None:
        """Set a nested property using dot notation.

        Args:
            path: Property path like 'base.name' or 'element.type'.
            value: Value to set.
        """
        parts = path.split(".")
        obj = self._document_properties
        for part in parts[:-1]:
            if part not in obj:
                obj[part] = {}
            obj = obj[part]
        obj[parts[-1]] = value

    def _get_nested_property(self, path: str, default: Any = None) -> Any:
        """Get a nested property using dot notation.

        Args:
            path: Property path like 'base.name'.
            default: Default value if path doesn't exist.

        Returns:
            The property value or default.
        """
        parts = path.split(".")
        obj = self._document_properties
        for part in parts:
            if isinstance(obj, dict) and part in obj:
                obj = obj[part]
            else:
                return default
        return obj

    # === File Management ===

    def has_files(self) -> bool:
        """Check if this document has any associated files.

        Returns:
            True if document has files, False otherwise.
        """
        files = self._document_properties.get("files", {})
        file_info = files.get("file_info", [])
        return bool(file_info)

    def add_file(
        self,
        name: str,
        location: str,
        ingest: bool | None = None,
        delete_original: bool | None = None,
        location_type: str | None = None,
    ) -> "ndi_document":
        """Add a file to this document.

        Args:
            name: The file record name for the document.
            location: File path or URL location.
            ingest: Whether to copy file into database (default: True for files,
                    False for URLs).
            delete_original: Whether to delete original after ingest.
            location_type: 'file', 'url', or 'ndicloud'.

        Returns:
            Self for method chaining.

        Raises:
            ValueError: If name is not in the document's file_list.
        """
        # Check if this document accepts files
        if "files" not in self._document_properties:
            raise ValueError("This document type does not accept files")

        # Validate name is in file_list
        b, msg, fi_index = self._is_in_file_list(name)
        if not b:
            raise ValueError(msg)

        # Detect location type
        location = location.strip()
        detected_type = "file"
        if location.lower().startswith(("http://", "https://")):
            detected_type = "url"
        elif location.lower().startswith("ndic://"):
            detected_type = "ndicloud"

        # Set defaults based on location type
        if ingest is None:
            ingest = detected_type == "file"
        if delete_original is None:
            delete_original = detected_type == "file"
        if location_type is None:
            location_type = detected_type

        # Generate unique ID for this file location
        uid = ndi_ido().id

        location_info = {
            "delete_original": delete_original,
            "uid": uid,
            "location": location,
            "parameters": "",
            "location_type": location_type,
            "ingest": ingest,
        }

        # Add to file_info
        if "file_info" not in self._document_properties["files"]:
            self._document_properties["files"]["file_info"] = []

        file_info = self._document_properties["files"]["file_info"]

        if fi_index is None:
            # New file entry
            file_info.append({"name": name, "locations": [location_info]})
        else:
            # Add location to existing file entry
            file_info[fi_index]["locations"].append(location_info)

        return self

    def remove_file(self, name: str, location: str | None = None) -> "ndi_document":
        """Remove file information from this document.

        Args:
            name: The file name to remove.
            location: Specific location to remove. If None, removes all locations.

        Returns:
            Self for method chaining.
        """
        b, msg, fi_index = self._is_in_file_list(name)
        if not b:
            raise ValueError(msg)

        if fi_index is None:
            return self  # Nothing to remove

        file_info = self._document_properties["files"]["file_info"]

        if location is None:
            # Remove entire file entry
            del file_info[fi_index]
        else:
            # Remove specific location
            locations = file_info[fi_index]["locations"]
            file_info[fi_index]["locations"] = [
                loc for loc in locations if loc["location"] != location
            ]
            # If no locations left, remove the file entry
            if not file_info[fi_index]["locations"]:
                del file_info[fi_index]

        return self

    def _is_in_file_list(self, name: str) -> tuple[bool, str, int | None]:
        """Check if a file name is valid for this document.

        Returns:
            Tuple of (is_valid, error_message, file_info_index)
        """
        if "files" not in self._document_properties:
            return False, "This document type does not accept files", None

        files = self._document_properties["files"]
        file_list = files.get("file_list", [])

        # Check for numbered file pattern (e.g., 'file_1' matches 'file_#')
        search_name = name
        if "_" in name:
            parts = name.rsplit("_", 1)
            if parts[1].isdigit():
                search_name = parts[0] + "_#"

        # Check if name is in file_list
        if name not in file_list and search_name not in file_list:
            return False, f"File '{name}' is not in this document's file_list", None

        # Find index in file_info if exists
        file_info = files.get("file_info", [])
        for i, fi in enumerate(file_info):
            if fi["name"] == name:
                return True, "", i

        return True, "", None

    def get_fuid(self, filename: str) -> str:
        """Return the file UID recorded for ``filename``, or ``''``.

        MATLAB equivalent: ``ndi.document/get_fuid``.  It is what
        ``ndi.fun.doc.findFuid`` and the session/dataset ``diff`` functions
        use to decide whether two documents point at the same stored file,
        so a missing one made those comparisons impossible to port.

        A file may have several locations; MATLAB returns the uid of the
        first, and so does this.

        Args:
            filename: The file record name to look up.

        Returns:
            The uid string, or ``''`` when the document has no files, does
            not declare this name, or has not had it added yet.
        """
        if not self.has_files():
            return ""

        b, _, fi_index = self._is_in_file_list(filename)
        if not b or fi_index is None:
            return ""

        locations = self._document_properties["files"]["file_info"][fi_index].get("locations", [])
        if not locations:
            return ""
        return locations[0].get("uid", "")

    def current_file_list(self) -> list[str]:
        """Return list of files currently associated with this document.

        Returns:
            List of file names that have been added to the document.
        """
        if "files" not in self._document_properties:
            return []
        file_info = self._document_properties["files"].get("file_info", [])
        return [fi["name"] for fi in file_info]

    # === Dependency Management ===

    def dependency(self) -> tuple[list[str], list[dict]]:
        """Return all dependencies for this document.

        Returns:
            Tuple of (names_list, dependency_structures)
        """
        depends_on = self._document_properties.get("depends_on", [])
        if not depends_on:
            return [], []

        names = [d["name"] for d in depends_on]
        return names, depends_on

    def dependency_value(self, dependency_name: str, error_if_not_found: bool = True) -> str | None:
        """Get the value of a dependency by name.

        Args:
            dependency_name: The name of the dependency.
            error_if_not_found: If True, raise error if not found.

        Returns:
            The dependency value (document ID), or None if not found.

        Raises:
            KeyError: If dependency not found and error_if_not_found is True.
        """
        depends_on = self._document_properties.get("depends_on", [])

        for dep in depends_on:
            if dep["name"].lower() == dependency_name.lower():
                return dep["value"]

        if error_if_not_found:
            raise KeyError(f"Dependency '{dependency_name}' not found")
        return None

    def dependency_value_n(
        self, dependency_name: str, error_if_not_found: bool = True
    ) -> list[str]:
        """Get values from a numbered dependency list.

        For dependencies like 'element_1', 'element_2', etc.

        Args:
            dependency_name: Base name (e.g., 'element' for 'element_1', 'element_2').
            error_if_not_found: If True, raise error if no matches found.

        Returns:
            List of dependency values in order.
        """
        depends_on = self._document_properties.get("depends_on", [])
        values = []
        i = 1
        while True:
            found = False
            for dep in depends_on:
                if dep["name"].lower() == f"{dependency_name}_{i}".lower():
                    values.append(dep["value"])
                    found = True
                    break
            if not found:
                break
            i += 1

        if not values and error_if_not_found:
            raise KeyError(f"No dependencies matching '{dependency_name}_*' found")
        return values

    def set_dependency_value(
        self, dependency_name: str, value: str, error_if_not_found: bool = True
    ) -> "ndi_document":
        """Set the value of a dependency.

        Args:
            dependency_name: The dependency name.
            value: The dependency value (document ID).
            error_if_not_found: If True and dependency doesn't exist, raise error.
                               If False, add the dependency.

        Returns:
            Self for method chaining.
        """
        if "depends_on" not in self._document_properties:
            if error_if_not_found:
                raise KeyError("ndi_document has no dependencies")
            self._document_properties["depends_on"] = []

        depends_on = self._document_properties["depends_on"]

        # Try to find existing
        for dep in depends_on:
            if dep["name"].lower() == dependency_name.lower():
                dep["value"] = value
                return self

        # Not found
        if error_if_not_found:
            raise KeyError(f"Dependency '{dependency_name}' not found")

        # Add new dependency
        depends_on.append({"name": dependency_name, "value": value})
        return self

    def add_dependency_value_n(self, dependency_name: str, value: str) -> "ndi_document":
        """Add a value to a numbered dependency list.

        Args:
            dependency_name: Base name (will create 'name_N' where N is next number).
            value: The dependency value to add.

        Returns:
            Self for method chaining.
        """
        existing = self.dependency_value_n(dependency_name, error_if_not_found=False)
        new_name = f"{dependency_name}_{len(existing) + 1}"
        return self.set_dependency_value(new_name, value, error_if_not_found=False)

    # === ndi_document Class Information ===

    def doc_unique_id(self) -> str:
        """Deprecated alias for :attr:`id`.

        MATLAB keeps ``doc_unique_id`` and warns
        ``'depricated..use ID() instead'`` on every call; this raises the
        same flag as a :class:`DeprecationWarning` so ported MATLAB code
        finds the method rather than an ``AttributeError``.

        Returns:
            The document's ``base.id``.
        """
        warnings.warn(
            "ndi_document.doc_unique_id() is deprecated; use .id instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        return self.id

    def doc_class(self) -> str:
        """Get the document class type.

        Returns:
            The class name (e.g., 'base', 'element', 'stimulus').
        """
        return self._document_properties.get("document_class", {}).get("class_name", "")

    def doc_superclass(self) -> list[str]:
        """Get the document's superclasses.

        Returns:
            List of superclass names.
        """
        doc_class = self._document_properties.get("document_class", {})
        superclasses = doc_class.get("superclasses", [])

        # MATLAB may store superclasses as a single dict instead of a list
        if isinstance(superclasses, dict):
            superclasses = [superclasses]

        sc_names = []
        for sc in superclasses:
            # Each superclass has a 'definition' pointing to its JSON
            # We need to read that to get the class_name
            definition = sc.get("definition", "")
            if definition:
                try:
                    sc_doc = ndi_document(_definition_to_doc_type(definition))
                    sc_names.append(sc_doc.doc_class())
                except Exception:
                    pass

        return list(set(sc_names))

    def doc_isa(self, document_class: str) -> bool:
        """Check if this document is of a specific class or inherits from it.

        Args:
            document_class: The class name to check.

        Returns:
            True if document is or inherits from the specified class.
        """
        all_classes = [self.doc_class()] + self.doc_superclass()
        return document_class in all_classes

    def write(
        self,
        filePrefix: str,
        indent: int = 2,
        *,
        writeLocalFiles: bool = False,
        session: Any = None,
    ) -> None:
        """Write the document properties to ``filePrefix + '.json'``.

        MATLAB equivalent: ``ndi.document/write``

        NOTE THE ARGUMENT IS A PREFIX, NOT A FILENAME. MATLAB writes
        ``[FILEPREFIX '.json']`` and names each associated file
        ``[FILEPREFIX '_' FILENAME]``, so the prefix identifies a SET of
        files, not one. Passing ``'doc.json'`` writes ``doc.json.json``.

        Args:
            filePrefix: Path prefix. ``'.json'`` is appended.
            indent: Indentation for pretty printing. Python-only; MATLAB's
                PrettyPrint is not adjustable.
            writeLocalFiles: If True, also write each associated file as
                ``filePrefix + '_' + name``.
            session: If given, read the associated files through this
                session's database rather than copying them from the
                locations recorded in the document.
        """
        json_path = Path(f"{filePrefix}.json")
        json_path.parent.mkdir(parents=True, exist_ok=True)
        with open(json_path, "w") as f:
            json.dump(_json_safe(self._document_properties), f, indent=indent)

        if writeLocalFiles:
            self._write_local_files(filePrefix, session)

    def _write_local_files(self, filePrefix: str, session: Any) -> None:
        """Write each associated file beside the JSON, as MATLAB's write does.

        With a session, the bytes come from the database. Without one,
        MATLAB copies the first location whose ``location_type`` is 'file'
        -- a URL or ndicloud location is not something it can copy -- and
        warns, rather than raising, when there is no such location.
        """
        file_info = self._document_properties.get("files", {}).get("file_info", [])
        if not isinstance(file_info, list):
            return

        for entry in file_info:
            name = entry.get("name", "")
            target = Path(f"{filePrefix}_{name}")

            if session is not None:
                handle = session.database_openbinarydoc(self, name)
                try:
                    target.write_bytes(handle.read())
                finally:
                    session.database_closebinarydoc(handle)
                continue

            for loc in entry.get("locations", []):
                if str(loc.get("location_type", "")).lower() == "file":
                    shutil.copyfile(loc.get("location", ""), target)
                    break
            else:
                warnings.warn(
                    f"Could not find local file location for {name}",
                    UserWarning,
                    stacklevel=2,
                )

    def remove_dependency_value_n(
        self,
        dependency_name: str,
        index: int | None = None,
    ) -> "ndi_document":
        """Remove a numbered dependency value.

        If index is None, removes all dependencies matching the base name.
        Otherwise removes the specific indexed dependency.

        Args:
            dependency_name: Base dependency name.
            index: Optional 1-based index to remove.

        Returns:
            Self for method chaining.
        """
        if "depends_on" not in self._document_properties:
            return self

        depends_on = self._document_properties["depends_on"]

        if index is not None:
            target = f"{dependency_name}_{index}"
            self._document_properties["depends_on"] = [d for d in depends_on if d["name"] != target]
        else:
            # Remove all matching the pattern
            import re

            pattern = re.compile(rf"^{re.escape(dependency_name)}_\d+$")
            self._document_properties["depends_on"] = [
                d for d in depends_on if not pattern.match(d["name"])
            ]

        return self

    # === Comparison and Merging ===

    def __eq__(self, other: "ndi_document") -> bool:
        """Check equality based on document ID."""
        if not isinstance(other, ndi_document):
            return False
        return self.id == other.id

    def __add__(self, other: "ndi_document") -> "ndi_document":
        """Merge two documents.

        The result has fields from both documents. Fields in self take
        precedence over fields in other for conflicts.

        Returns:
            New ndi_document with merged properties.
        """
        result = ndi_document(self._document_properties)

        # Merge superclasses
        my_sc = result._document_properties.get("document_class", {}).get("superclasses", [])
        other_sc = other._document_properties.get("document_class", {}).get("superclasses", [])
        result._document_properties["document_class"]["superclasses"] = my_sc + other_sc

        # Merge dependencies
        if "depends_on" in other._document_properties:
            if "depends_on" not in result._document_properties:
                result._document_properties["depends_on"] = []
            for dep in other._document_properties["depends_on"]:
                existing = [
                    d for d in result._document_properties["depends_on"] if d["name"] == dep["name"]
                ]
                if existing:
                    existing[0]["value"] = dep["value"]
                else:
                    result._document_properties["depends_on"].append(dep)

        # Merge file_list
        if "files" in other._document_properties:
            if "files" not in result._document_properties:
                result._document_properties["files"] = other._document_properties["files"]
            else:
                my_files = result._document_properties["files"].get("file_list", [])
                other_files = other._document_properties["files"].get("file_list", [])
                result._document_properties["files"]["file_list"] = list(
                    set(my_files + other_files)
                )

        # Merge other fields (other's fields added if not in self)
        for key, value in other._document_properties.items():
            if key not in ["document_class", "depends_on", "files", "base"]:
                if key not in result._document_properties:
                    result._document_properties[key] = deepcopy(value)

        return result

    # === Conversion ===

    @staticmethod
    def _table_abbreviations() -> list[tuple[str, str]]:
        """Read the column-name abbreviations MATLAB's ``to_table`` applies.

        ``ndi_common/config/ndi_document2table_abbreviations.json`` is a list
        of ``[from, to]`` pairs -- ``orientation_direction_tuning`` becomes
        ``oridir``, ``significance`` becomes ``sig``, and so on.  The file
        ships in this repository too; it was simply never read here.

        Returns:
            The pairs in file order.  Order matters: the replacements are
            substring replacements applied in sequence, and
            ``orientation_direction_tuning`` must be shortened before the
            later ``orientation`` pair can reach what is left.
        """
        path = ndi_common_PathConstants.COMMON_FOLDER / "config" / _TABLE_ABBREVIATION_FILE
        if not path.is_file():
            return []
        try:
            with open(path) as f:
                pairs = json.load(f)
        except (OSError, ValueError):
            return []
        return [
            (str(pair[0]), str(pair[1]))
            for pair in pairs
            if isinstance(pair, (list, tuple)) and len(pair) == 2
        ]

    def to_table(self) -> "pd.DataFrame":
        """Convert document to a single-row pandas DataFrame.

        Mirrors MATLAB's ``ndi.document/to_table``: one
        ``depends_on_<name>`` column per dependency, then the remaining
        properties flattened with ``.`` between levels and the abbreviations
        above applied to the resulting names.

        Returns:
            DataFrame with document properties as columns.

        Raises:
            ImportError: If pandas is not installed.
        """
        if not HAS_PANDAS:
            raise ImportError("pandas is required for to_table()")

        data: dict[str, Any] = {}

        # Add dependencies
        names, deps = self.dependency()
        for dep in deps:
            data[f"depends_on_{dep['name']}"] = dep["value"]

        # MATLAB drops 'depends_on' and 'files' with rmfield, which reaches
        # the TOP LEVEL ONLY.  Skipping those two names at every depth, as
        # this did, silently deleted any same-named field nested inside
        # another property.
        properties = {
            key: value
            for key, value in self._document_properties.items()
            if key not in ("depends_on", "files")
        }

        flat: dict[str, Any] = {}

        def flatten(obj, prefix=""):
            for key, value in obj.items():
                full_key = f"{prefix}{key}"
                if isinstance(value, dict):
                    flatten(value, f"{full_key}.")
                elif _is_struct_array(value):
                    # vlt.data.flattenstruct2table's struct-array case: a
                    # list of records becomes one column per sub-field
                    # holding every record's value, rather than one column
                    # holding the raw list.  A one-element list is a scalar
                    # struct in MATLAB and recurses normally.
                    if len(value) == 1:
                        flatten(value[0], f"{full_key}.")
                    else:
                        for sub_key in value[0]:
                            flat[f"{full_key}.{sub_key}"] = [
                                record.get(sub_key) for record in value
                            ]
                else:
                    flat[full_key] = value

        flatten(properties)

        abbreviations = self._table_abbreviations()
        for name, value in flat.items():
            for old, new in abbreviations:
                name = name.replace(old, new)
            data[name] = value

        return pd.DataFrame([data])

    def to_dict(self) -> dict:
        """Convert document to a plain dictionary.

        Returns:
            Copy of document_properties.
        """
        return deepcopy(self._document_properties)

    def to_json(self, indent: int = 2) -> str:
        """Convert document to JSON string.

        Args:
            indent: Indentation level for pretty printing.

        Returns:
            JSON string representation.
        """
        return json.dumps(self._document_properties, indent=indent)

    def setproperties(self, **kwargs) -> "ndi_document":
        """Set multiple properties at once.

        Args:
            **kwargs: Property paths and values (e.g., base_name='test').
                      Underscores are converted to dots for nested access.

        Returns:
            Self for method chaining.

        Example:
            doc.setproperties(**{'base.name': 'new_name', 'element.type': 'probe'})
        """
        for key, value in kwargs.items():
            self._set_nested_property(key, value)
        return self

    def validate(self, session=None):
        """Validate document against its schema.

        Three-tier validation:
          1. This-class properties: type checking against schema
          2. Superclass properties: walk hierarchy
          3. Dependency references: check depends_on targets exist

        Args:
            session: Optional session for dependency checking.

        Returns:
            ValidationResult with is_valid flag and error details.
            Bool-coercible: ``if doc.validate(): ...``
        """
        from .validate import validate as _validate

        return _validate(self, session=session)

    # === Static Methods ===

    @staticmethod
    def find_doc_by_id(
        doc_array: list["ndi_document"], doc_id: str
    ) -> tuple[Optional["ndi_document"], int | None]:
        """Find a document in a list by its ID.

        Args:
            doc_array: List of ndi_document objects.
            doc_id: The ID to search for.

        Returns:
            Tuple of (document, index) or (None, None) if not found.
        """
        for i, doc in enumerate(doc_array):
            if doc.id == doc_id:
                return doc, i
        return None, None

    @staticmethod
    def find_newest(doc_array: list["ndi_document"]) -> tuple["ndi_document", int, datetime]:
        """Find the newest document in a list.

        Args:
            doc_array: List of ndi_document objects.

        Returns:
            Tuple of (newest_document, index, datestamp).
        """
        if not doc_array:
            raise ValueError("ndi_document array is empty")

        timestamps = []
        for doc in doc_array:
            ds = doc._document_properties.get("base", {}).get("datestamp", "")
            if ds:
                # Parse ISO format timestamp
                try:
                    ts = datetime.fromisoformat(ds.replace("Z", "+00:00"))
                except ValueError:
                    ts = datetime.min.replace(tzinfo=timezone.utc)
            else:
                ts = datetime.min.replace(tzinfo=timezone.utc)
            timestamps.append(ts)

        newest_idx = max(range(len(timestamps)), key=lambda i: timestamps[i])
        return doc_array[newest_idx], newest_idx, timestamps[newest_idx]

    @staticmethod
    def read_blank_definition(document_type: str) -> dict:
        """Read a blank document definition from JSON schema.

        Args:
            document_type: The document type name (without .json extension).

        Returns:
            Dictionary with blank document structure.
        """
        root = ndi_common_PathConstants.DOCUMENT_PATH
        json_path = root / f"{document_type}.json"

        if not json_path.exists() and "/" not in document_type:
            # Fall back to a recursive search for a BARE class name.
            #
            # MATLAB resolves a bare name against the whole document tree,
            # so ndi.document('image') finds data/image.json. Here only the
            # top level was tried, so the same call needed 'data/image' --
            # a difference affecting every document in a subdirectory
            # (image, generic_file, the whole stimulus family) and one that
            # made otherwise-symmetric code diverge at the call site.
            #
            # Only for a bare name: a caller who wrote 'data/image'
            # expects that exact file, and should not silently get a
            # same-named document from elsewhere in the tree.
            matches = sorted(root.rglob(f"{document_type}.json"))
            if len(matches) == 1:
                json_path = matches[0]
            elif len(matches) > 1:
                rel = ", ".join(str(m.relative_to(root)) for m in matches)
                raise FileNotFoundError(
                    f"ndi_document type {document_type!r} is ambiguous: {rel}. "
                    f"Give the path, e.g. {matches[0].relative_to(root).with_suffix('')}."
                )

        if not json_path.exists():
            raise FileNotFoundError(
                f"ndi_document definition not found: {json_path}. "
                f"Make sure NDI is properly installed."
            )

        with open(json_path) as f:
            definition = json.load(f)

        # Process superclasses recursively.
        #
        # Three things are inherited, matching did.document._merge_superclasses
        # and MATLAB's did.document: property groups, the dependency list, and
        # the superclass list itself.  The last two were missing here, which is
        # why documents built by NDI-python carried only their *direct*
        # superclasses and only their *own* dependencies, while the schemas --
        # written against MATLAB, where DID flattens both -- declare the
        # transitive closure.  DID-python's validator compares the two, so the
        # gap turned into "Dissimilar superclasses defined/found" on every
        # ingestion document the moment add_docs began validating.
        class_props = definition.get("document_class")
        raw_superclasses = class_props.get("superclasses") if class_props else None
        if isinstance(raw_superclasses, dict):  # MATLAB unwraps a 1-element cell
            raw_superclasses = [raw_superclasses]

        if raw_superclasses:
            merged_superclasses: list[dict] = []
            for sc in raw_superclasses:
                sc_def = sc.get("definition", "") if isinstance(sc, dict) else sc
                if not sc_def:
                    continue

                entry = dict(sc) if isinstance(sc, dict) else {"definition": sc_def}
                merged_superclasses.append(entry)

                # Strip whatever $...PATH/ prefix the definition carries, not
                # just $NDIDOCUMENTPATH: calculator documents name their
                # superclasses through $NDICALCDOCUMENTPATH, and ndi_install.py
                # merges every dependency's ndi_common into one tree.
                sc_type = _definition_to_doc_type(sc_def)
                try:
                    sc_props = ndi_document.read_blank_definition(sc_type)
                except FileNotFoundError:
                    # Warn rather than swallow. A declared superclass that
                    # cannot be found is a broken definition, and the document
                    # silently loses everything that superclass would have
                    # contributed -- including 'base'. That surfaced far away
                    # as KeyError: 'base' at construction and took a bisect to
                    # trace back here. Raising would be better still, but is a
                    # wider behavioural change than this fix.
                    #
                    # The entry stays in the list either way: dropping it would
                    # silently shorten the superclass list the schema is
                    # validated against, trading one quiet failure for another.
                    warnings.warn(
                        f"superclass {sc_def!r} of {document_type!r} could "
                        f"not be resolved (looked for {sc_type!r}); the "
                        f"document will be missing whatever it defines",
                        RuntimeWarning,
                        stacklevel=2,
                    )
                    continue

                # The superclass's own superclasses join ours.  sc_props is
                # already merged, so this is the whole transitive closure.
                sc_class = sc_props.get("document_class") or {}
                inherited = sc_class.get("superclasses")
                if isinstance(inherited, dict):
                    inherited = [inherited]
                for item in inherited or []:
                    if isinstance(item, dict) and "definition" in item:
                        merged_superclasses.append(dict(item))

                # Dependencies are unioned by name, this class winning.
                own_depends = definition.get("depends_on")
                sc_depends = sc_props.get("depends_on")
                if isinstance(own_depends, dict):
                    own_depends = [own_depends]
                if isinstance(sc_depends, dict):
                    sc_depends = [sc_depends]
                if sc_depends:
                    seen_names = set()
                    unique_depends = []
                    for dependency in list(own_depends or []) + list(sc_depends):
                        name = (
                            dependency.get("name") if isinstance(dependency, dict) else dependency
                        )
                        if name in seen_names:
                            continue
                        seen_names.add(name)
                        unique_depends.append(dependency)
                    definition["depends_on"] = unique_depends

                # Merge superclass properties
                for key, value in sc_props.items():
                    if key not in ("document_class", "depends_on") and key not in definition:
                        definition[key] = value

            # Unique by definition string, preserving order.
            seen_definitions = set()
            unique_superclasses = []
            for entry in merged_superclasses:
                sc_def = entry.get("definition")
                if sc_def in seen_definitions:
                    continue
                seen_definitions.add(sc_def)
                unique_superclasses.append(entry)
            definition["document_class"]["superclasses"] = unique_superclasses

        return definition

    def __repr__(self) -> str:
        return f"ndi_document('{self.doc_class()}', id='{self.id}')"


# Pythonic alias
Document = ndi_document
